import '../../models/ingredient.dart';

const List<String> kImplicitIngredients = [
  'Tuz',
  'Karabiber',
  'Pul Biber',
  'Zeytinyağı',
  'Ayçiçek Yağı',
  'Su',
  'Un',
  'Sarımsak',
  'Kuru Soğan',
  'Salça',
];

final List<Ingredient> kInitialIngredients = [
  // === SEBZELER ===
  Ingredient(id: 'domates', name: 'Domates', category: 'Sebzeler'),
  Ingredient(id: 'patates', name: 'Patates', category: 'Sebzeler'),
  Ingredient(id: 'biber', name: 'Biber', category: 'Sebzeler'),
  Ingredient(id: 'havuc', name: 'Havuç', category: 'Sebzeler'),
  Ingredient(id: 'ispanak', name: 'Ispanak', category: 'Sebzeler'),
  Ingredient(id: 'patlican', name: 'Patlıcan', category: 'Sebzeler'),
  Ingredient(id: 'kabak', name: 'Kabak', category: 'Sebzeler'),
  Ingredient(id: 'brokoli', name: 'Brokoli', category: 'Sebzeler'),
  Ingredient(id: 'karnabahar', name: 'Karnabahar', category: 'Sebzeler'),
  Ingredient(id: 'pirasa', name: 'Pırasa', category: 'Sebzeler'),
  Ingredient(id: 'kereviz', name: 'Kereviz', category: 'Sebzeler'),
  Ingredient(id: 'bezelye', name: 'Bezelye', category: 'Sebzeler'),
  Ingredient(id: 'taze_fasulye', name: 'Taze Fasulye', category: 'Sebzeler'),
  Ingredient(id: 'marul', name: 'Marul', category: 'Sebzeler'),
  Ingredient(id: 'maydanoz', name: 'Maydanoz', category: 'Sebzeler'),
  Ingredient(id: 'dereotu', name: 'Dereotu', category: 'Sebzeler'),
  Ingredient(id: 'nane_taze', name: 'Taze Nane', category: 'Sebzeler'),
  Ingredient(id: 'salatalik', name: 'Salatalık', category: 'Sebzeler'),
  Ingredient(id: 'roka', name: 'Roka', category: 'Sebzeler'),
  Ingredient(id: 'tere', name: 'Tere', category: 'Sebzeler'),
  Ingredient(id: 'lahana', name: 'Lahana', category: 'Sebzeler'),
  Ingredient(id: 'kirmizi_lahana', name: 'Kırmızı Lahana', category: 'Sebzeler'),
  Ingredient(id: 'bruksel_lahana', name: 'Brüksel Lahanası', category: 'Sebzeler'),
  Ingredient(id: 'kuskonmaz', name: 'Kuşkonmaz', category: 'Sebzeler'),
  Ingredient(id: 'mantar', name: 'Mantar', category: 'Sebzeler'),
  Ingredient(id: 'istiridye_mantari', name: 'İstiridye Mantarı', category: 'Sebzeler'),
  Ingredient(id: 'sitake_mantari', name: 'Şitake Mantarı', category: 'Sebzeler'),
  Ingredient(id: 'balkabagı', name: 'Balkabağı', category: 'Sebzeler'),
  Ingredient(id: 'enginar', name: 'Enginar', category: 'Sebzeler'),
  Ingredient(id: 'bamya', name: 'Bamya', category: 'Sebzeler'),
  Ingredient(id: 'semizotu', name: 'Semizotu', category: 'Sebzeler'),
  Ingredient(id: 'turp', name: 'Turp', category: 'Sebzeler'),
  Ingredient(id: 'pancar', name: 'Pancar', category: 'Sebzeler'),
  Ingredient(id: 'misir', name: 'Mısır', category: 'Sebzeler'),
  Ingredient(id: 'yesil_sogan', name: 'Yeşil Soğan', category: 'Sebzeler'),
  Ingredient(id: 'asma_yapragi', name: 'Asma Yaprağı', category: 'Sebzeler'),
  Ingredient(id: 'tofu', name: 'Tofu', category: 'Sebzeler'),
  Ingredient(id: 'tempeh', name: 'Tempeh', category: 'Sebzeler'),

  // === BAKLİYATLAR & TAHILLAR ===
  Ingredient(id: 'kirmizi_mercimek', name: 'Kırmızı Mercimek', category: 'Bakliyatlar'),
  Ingredient(id: 'yesil_mercimek', name: 'Yeşil Mercimek', category: 'Bakliyatlar'),
  Ingredient(id: 'nohut', name: 'Nohut', category: 'Bakliyatlar'),
  Ingredient(id: 'kuru_fasulye', name: 'Kuru Fasulye', category: 'Bakliyatlar'),
  Ingredient(id: 'pirinc', name: 'Pirinç', category: 'Bakliyatlar'),
  Ingredient(id: 'bulgur', name: 'Bulgur', category: 'Bakliyatlar'),
  Ingredient(id: 'barbunya', name: 'Barbunya', category: 'Bakliyatlar'),
  Ingredient(id: 'mas_fasulyesi', name: 'Maş Fasulyesi', category: 'Bakliyatlar'),
  Ingredient(id: 'bakla', name: 'Bakla', category: 'Bakliyatlar'),
  Ingredient(id: 'yulaf_ezmesi', name: 'Yulaf Ezmesi', category: 'Bakliyatlar'),
  Ingredient(id: 'kinoa', name: 'Kinoa', category: 'Bakliyatlar'),
  Ingredient(id: 'karabugday', name: 'Karabuğday (Greçka)', category: 'Bakliyatlar'),
  Ingredient(id: 'chia_tohumu', name: 'Chia Tohumu', category: 'Bakliyatlar'),
  Ingredient(id: 'keten_tohumu', name: 'Keten Tohumu', category: 'Bakliyatlar'),
  Ingredient(id: 'susam', name: 'Susam', category: 'Bakliyatlar'),
  Ingredient(id: 'corek_otu', name: 'Çörek Otu', category: 'Bakliyatlar'),
  Ingredient(id: 'irmik', name: 'İrmik', category: 'Bakliyatlar'),
  Ingredient(id: 'arpa_sehriye', name: 'Arpa Şehriye', category: 'Bakliyatlar'),
  Ingredient(id: 'tel_sehriye', name: 'Tel Şehriye', category: 'Bakliyatlar'),
  Ingredient(id: 'misir_unu', name: 'Mısır Unu', category: 'Bakliyatlar'),
  Ingredient(id: 'tam_bugday_unu', name: 'Tam Buğday Unu', category: 'Bakliyatlar'),
  Ingredient(id: 'siyez_unu', name: 'Siyez Unu', category: 'Bakliyatlar'),
  Ingredient(id: 'cavdar_unu', name: 'Çavdar Unu', category: 'Bakliyatlar'),
  Ingredient(id: 'yulaf_unu', name: 'Yulaf Unu', category: 'Bakliyatlar'),
  Ingredient(id: 'badem_unu', name: 'Badem Unu', category: 'Bakliyatlar'),
  Ingredient(id: 'hindistan_cevizi_unu', name: 'Hindistan Cevizi Unu', category: 'Bakliyatlar'),

  // === ET & BALIK ÜRÜNLERİ ===
  Ingredient(id: 'tavuk_gogsu', name: 'Tavuk Göğsü', category: 'Et & Balık Ürünleri'),
  Ingredient(id: 'tavuk_baget', name: 'Tavuk Baget', category: 'Et & Balık Ürünleri'),
  Ingredient(id: 'tavuk_pirzola', name: 'Tavuk Pirzola', category: 'Et & Balık Ürünleri'),
  Ingredient(id: 'butun_tavuk', name: 'Bütün Tavuk', category: 'Et & Balık Ürünleri'),
  Ingredient(id: 'dana_kiyma', name: 'Dana Kıyma', category: 'Et & Balık Ürünleri'),
  Ingredient(id: 'kusbasi_et', name: 'Kuşbaşı Dana Eti', category: 'Et & Balık Ürünleri'),
  Ingredient(id: 'dana_antrikot', name: 'Dana Antrikot', category: 'Et & Balık Ürünleri'),
  Ingredient(id: 'kuzu_eti', name: 'Kuzu Eti', category: 'Et & Balık Ürünleri'),
  Ingredient(id: 'kuzu_pirzola', name: 'Kuzu Pirzola', category: 'Et & Balık Ürünleri'),
  Ingredient(id: 'ton_baligi', name: 'Ton Balığı', category: 'Et & Balık Ürünleri'),
  Ingredient(id: 'somon', name: 'Somon', category: 'Et & Balık Ürünleri'),
  Ingredient(id: 'levrek', name: 'Levrek', category: 'Et & Balık Ürünleri'),
  Ingredient(id: 'cipura', name: 'Çipura', category: 'Et & Balık Ürünleri'),
  Ingredient(id: 'hamsi', name: 'Hamsi', category: 'Et & Balık Ürünleri'),
  Ingredient(id: 'karides', name: 'Karides', category: 'Et & Balık Ürünleri'),
  Ingredient(id: 'kalamar', name: 'Kalamar', category: 'Et & Balık Ürünleri'),
  Ingredient(id: 'hindi_fume', name: 'Hindi Füme', category: 'Et & Balık Ürünleri'),
  Ingredient(id: 'sucuk', name: 'Sucuk', category: 'Et & Balık Ürünleri'),
  Ingredient(id: 'pastirma', name: 'Pastırma', category: 'Et & Balık Ürünleri'),
  Ingredient(id: 'salam', name: 'Salam', category: 'Et & Balık Ürünleri'),
  Ingredient(id: 'sosis', name: 'Sosis', category: 'Et & Balık Ürünleri'),

  // === SÜT ÜRÜNLERİ & YUMURTA ===
  Ingredient(id: 'sut', name: 'Süt', category: 'Süt Ürünleri'),
  Ingredient(id: 'yogurt', name: 'Yoğurt', category: 'Süt Ürünleri'),
  Ingredient(id: 'suzme_yogurt', name: 'Süzme Yoğurt', category: 'Süt Ürünleri'),
  Ingredient(id: 'beyaz_peynir', name: 'Beyaz Peynir', category: 'Süt Ürünleri'),
  Ingredient(id: 'kasar_peyniri', name: 'Kaşar Peyniri', category: 'Süt Ürünleri'),
  Ingredient(id: 'lor_peyniri', name: 'Lor Peyniri', category: 'Süt Ürünleri'),
  Ingredient(id: 'suzme_peynir', name: 'Süzme Peynir', category: 'Süt Ürünleri'),
  Ingredient(id: 'tereyagi', name: 'Tereyağı', category: 'Süt Ürünleri'),
  Ingredient(id: 'yumurta', name: 'Yumurta', category: 'Süt Ürünleri'),
  Ingredient(id: 'labne_peyniri', name: 'Labne Peyniri', category: 'Süt Ürünleri'),
  Ingredient(id: 'tulum_peyniri', name: 'Tulum Peyniri', category: 'Süt Ürünleri'),
  Ingredient(id: 'ezine_peyniri', name: 'Ezine Peyniri', category: 'Süt Ürünleri'),
  Ingredient(id: 'hellim_peyniri', name: 'Hellim Peyniri', category: 'Süt Ürünleri'),
  Ingredient(id: 'krem_peynir', name: 'Krem Peynir', category: 'Süt Ürünleri'),
  Ingredient(id: 'krema', name: 'Krema', category: 'Süt Ürünleri'),
  Ingredient(id: 'kefir', name: 'Kefir', category: 'Süt Ürünleri'),
  Ingredient(id: 'kaymak', name: 'Kaymak', category: 'Süt Ürünleri'),
  Ingredient(id: 'badem_sutu', name: 'Badem Sütü', category: 'Süt Ürünleri'),
  Ingredient(id: 'yulaf_sutu', name: 'Yulaf Sütü', category: 'Süt Ürünleri'),
  Ingredient(id: 'hindistan_cevizi_sutu', name: 'Hindistan Cevizi Sütü', category: 'Süt Ürünleri'),

  // === MEYVELER (DİĞER) ===
  Ingredient(id: 'limon', name: 'Limon', category: 'Diğer'),
  Ingredient(id: 'elma', name: 'Elma', category: 'Diğer'),
  Ingredient(id: 'armut', name: 'Armut', category: 'Diğer'),
  Ingredient(id: 'muz', name: 'Muz', category: 'Diğer'),
  Ingredient(id: 'portakal', name: 'Portakal', category: 'Diğer'),
  Ingredient(id: 'mandalina', name: 'Mandalina', category: 'Diğer'),
  Ingredient(id: 'greyfurt', name: 'Greyfurt', category: 'Diğer'),
  Ingredient(id: 'cilek', name: 'Çilek', category: 'Diğer'),
  Ingredient(id: 'kiraz', name: 'Kiraz', category: 'Diğer'),
  Ingredient(id: 'erik', name: 'Erik', category: 'Diğer'),
  Ingredient(id: 'seftali', name: 'Şeftali', category: 'Diğer'),
  Ingredient(id: 'kayisi', name: 'Kayısı', category: 'Diğer'),
  Ingredient(id: 'incir', name: 'İncir', category: 'Diğer'),
  Ingredient(id: 'uzum', name: 'Üzüm', category: 'Diğer'),
  Ingredient(id: 'karpuz', name: 'Karpuz', category: 'Diğer'),
  Ingredient(id: 'kavun', name: 'Kavun', category: 'Diğer'),
  Ingredient(id: 'nar', name: 'Nar', category: 'Diğer'),
  Ingredient(id: 'ayva', name: 'Ayva', category: 'Diğer'),
  Ingredient(id: 'frambuaz', name: 'Frambuaz', category: 'Diğer'),
  Ingredient(id: 'yaban_mersini', name: 'Yaban Mersini', category: 'Diğer'),
  Ingredient(id: 'avokado', name: 'Avokado', category: 'Diğer'),
  Ingredient(id: 'hurma', name: 'Hurma', category: 'Diğer'),

  // === KURUYEMİŞLER & TOHUMLAR ===
  Ingredient(id: 'ceviz', name: 'Ceviz', category: 'Diğer'),
  Ingredient(id: 'badem', name: 'Badem', category: 'Diğer'),
  Ingredient(id: 'findik', name: 'Fındık', category: 'Diğer'),
  Ingredient(id: 'fistik', name: 'Fıstık', category: 'Diğer'),
  Ingredient(id: 'antep_fistigi', name: 'Antep Fıstığı', category: 'Diğer'),
  Ingredient(id: 'kaju', name: 'Kaju', category: 'Diğer'),
  Ingredient(id: 'kabak_cekirdegi', name: 'Kabak Çekirdeği', category: 'Diğer'),
  Ingredient(id: 'ay_cekirdegi', name: 'Ay Çekirdeği', category: 'Diğer'),
  Ingredient(id: 'kuru_uzum', name: 'Kuru Üzüm', category: 'Diğer'),
  Ingredient(id: 'kuru_kayisi', name: 'Kuru Kayısı', category: 'Diğer'),
  Ingredient(id: 'kuru_incir', name: 'Kuru İncir', category: 'Diğer'),
  
  // === SOSLAR, YAĞLAR & BAHARATLAR ===
  Ingredient(id: 'makarna', name: 'Makarna', category: 'Diğer'),
  Ingredient(id: 'zeytin_siyah', name: 'Siyah Zeytin', category: 'Diğer'),
  Ingredient(id: 'zeytin_yesil', name: 'Yeşil Zeytin', category: 'Diğer'),
  Ingredient(id: 'bal', name: 'Bal', category: 'Diğer'),
  Ingredient(id: 'pekmez', name: 'Pekmez', category: 'Diğer'),
  Ingredient(id: 'tahin', name: 'Tahin', category: 'Diğer'),
  Ingredient(id: 'kakao_tozu', name: 'Kakao Tozu', category: 'Diğer'),
  Ingredient(id: 'kakao_parcaciklari', name: 'Kakao Parçacıkları', category: 'Diğer'),
  Ingredient(id: 'maca_tozu', name: 'Maça Tozu', category: 'Diğer'),
  Ingredient(id: 'yer_fistigi_ezmesi', name: 'Yer Fıstığı Ezmesi', category: 'Diğer'),
  Ingredient(id: 'badem_ezmesi', name: 'Badem Ezmesi', category: 'Diğer'),
  Ingredient(id: 'sirke', name: 'Sirke', category: 'Diğer'),
  Ingredient(id: 'nar_eksisi', name: 'Nar Ekşisi', category: 'Diğer'),
  Ingredient(id: 'akcaagac_surubu', name: 'Akçaağaç Şurubu', category: 'Diğer'),
  Ingredient(id: 'avokado_yagi', name: 'Avokado Yağı', category: 'Diğer'),
  Ingredient(id: 'hindistan_cevizi_yagi', name: 'Hindistan Cevizi Yağı', category: 'Diğer'),
  Ingredient(id: 'truf_yagi', name: 'Trüf Yağı', category: 'Diğer'),
  Ingredient(id: 'hindistan_cevizi_sekeri', name: 'Hindistan Cevizi Şekeri', category: 'Diğer'),
  Ingredient(id: 'vanilya_ozutu', name: 'Vanilya Özütü', category: 'Diğer'),
  Ingredient(id: 'kimyon', name: 'Kimyon', category: 'Diğer'),
  Ingredient(id: 'kekik', name: 'Kekik', category: 'Diğer'),
  Ingredient(id: 'zerdecal', name: 'Zerdeçal', category: 'Diğer'),
  Ingredient(id: 'zencefil', name: 'Zencefil', category: 'Diğer'),
  Ingredient(id: 'tarcin', name: 'Tarçın', category: 'Diğer'),
  Ingredient(id: 'sumak', name: 'Sumak', category: 'Diğer'),
  Ingredient(id: 'yenibahar', name: 'Yenibahar', category: 'Diğer'),
  Ingredient(id: 'biberiye', name: 'Biberiye', category: 'Diğer'),
];
